import { motion } from 'framer-motion';
import { Dices, Save, Trash2, Trophy } from 'lucide-react';
import { useEffect, useMemo, useState } from 'react';
import { Link, useParams } from 'react-router-dom';
import { AdminLayout } from '../components/AdminLayout';
import { BracketView } from '../components/BracketView';
import { addTournamentPlayer, buildScorers, closeMatch, getTournament, listMatches, listPlayers, listTournamentPlayers, removeTournamentPlayer, runDraw } from '../lib/firestore';
import { ScorersTable } from '../components/ScorersTable';
export function AdminTournamentPage() {
    const { id = '' } = useParams();
    const [tournament, setTournament] = useState(null);
    const [players, setPlayers] = useState([]);
    const [parts, setParts] = useState([]);
    const [matches, setMatches] = useState([]);
    const [selected, setSelected] = useState(null);
    const [scorers, setScorers] = useState([]);
    const [drawing, setDrawing] = useState(false);
    const refresh = async () => { setTournament(await getTournament(id)); setPlayers(await listPlayers()); setParts(await listTournamentPlayers(id)); setMatches(await listMatches(id)); setScorers(await buildScorers(id)); };
    useEffect(() => { void refresh(); }, [id]);
    const available = useMemo(() => players.filter((p) => !parts.some((part) => part.playerId === p.id)), [players, parts]);
    return <AdminLayout><div className="space-y-6"><section className="glass rounded-[2rem] p-5"><div className="flex flex-wrap items-center justify-between gap-4"><div><p className="text-xs font-black uppercase tracking-[.3em] text-electric">Gestión de torneo</p><h1 className="text-4xl font-black">{tournament?.name ?? 'Torneo'}</h1><p className="text-sm text-slate-400">{parts.length}/16 jugadores · estado {tournament?.status}</p></div><div className="flex flex-wrap gap-2"><Link className="btn btn-ghost" to={`/tournament/${id}`}>Vista pública</Link><button disabled={parts.length !== 16 || matches.length > 0 || drawing} className="btn btn-primary disabled:opacity-40" onClick={async () => { setDrawing(true); await new Promise((r) => setTimeout(r, 1400)); await runDraw(id); setDrawing(false); await refresh(); }}><Dices className="h-4 w-4"/> Sortear cruces</button></div></div>{drawing && <motion.div initial={{ scale: .95, opacity: 0 }} animate={{ scale: 1, opacity: 1 }} className="mt-5 rounded-3xl border border-electric/30 bg-electric/10 p-5 text-center text-2xl font-black">🎲 La arena decide los cruces...</motion.div>}</section><div className="grid gap-6 xl:grid-cols-[360px_1fr]"><aside className="space-y-5"><section className="glass rounded-3xl p-4"><h2 className="font-black">Agregar jugadores</h2><div className="mt-3 max-h-72 space-y-2 overflow-auto pr-1">{available.map((player) => <button key={player.id} disabled={parts.length >= 16} className="btn btn-ghost w-full justify-between" onClick={() => addTournamentPlayer(id, player).then(refresh)}><span>{player.nickname}</span><span className="text-xs text-slate-400">{player.currentTeam}</span></button>)}</div></section><section className="glass rounded-3xl p-4"><h2 className="font-black">Plantel ({parts.length}/16)</h2><div className="mt-3 space-y-2">{parts.map((part) => <div key={part.id} className="flex items-center justify-between rounded-2xl bg-white/5 p-3"><span><b>{part.playerNickname}</b><p className="text-xs text-slate-400">{part.teamName}</p></span><button onClick={() => removeTournamentPlayer(part.id).then(refresh)}><Trash2 className="h-4 w-4 text-danger"/></button></div>)}</div></section><section className="glass rounded-3xl p-4"><h2 className="mb-3 font-black">Tabla goleadores</h2><ScorersTable rows={scorers}/></section></aside><section className="space-y-4"><BracketView matches={matches} onMatchClick={setSelected}/></section></div>{selected && <ResultModal match={selected} onClose={() => setSelected(null)} onSaved={async () => { setSelected(null); await refresh(); }}/>}</div></AdminLayout>;
}
function ResultModal({ match, onClose, onSaved }) {
    const [scoreA, setScoreA] = useState(match.scoreA ?? 0);
    const [scoreB, setScoreB] = useState(match.scoreB ?? 0);
    const [goals, setGoals] = useState([{ playerOwnerId: match.playerAId || '', playerOwnerName: match.playerAName, scorerName: '', quantity: 1 }, { playerOwnerId: match.playerBId || '', playerOwnerName: match.playerBName, scorerName: '', quantity: 1 }]);
    return <div className="fixed inset-0 z-50 grid place-items-center bg-black/70 p-4 backdrop-blur-sm"><div className="glass w-full max-w-xl rounded-[2rem] p-5 shadow-card"><div className="flex items-start justify-between"><div><p className="text-xs font-black uppercase tracking-[.3em] text-electric">Carga rápida</p><h2 className="text-2xl font-black">{match.playerAName} vs {match.playerBName}</h2></div><button className="btn btn-ghost" onClick={onClose}>Cerrar</button></div><div className="my-6 grid grid-cols-[1fr_auto_1fr] items-center gap-3"><ScoreBox name={match.playerAName || 'A'} value={scoreA} setValue={setScoreA}/><span className="text-2xl font-black text-slate-500">VS</span><ScoreBox name={match.playerBName || 'B'} value={scoreB} setValue={setScoreB}/></div><div className="space-y-2"><p className="text-sm font-black">Goleadores rápidos</p>{goals.map((goal, index) => <div key={index} className="grid grid-cols-[1fr_1fr_80px] gap-2"><select className="input" value={goal.playerOwnerId} onChange={(e) => setGoals(goals.map((g, i) => i === index ? { ...g, playerOwnerId: e.target.value, playerOwnerName: e.target.value === match.playerAId ? match.playerAName : match.playerBName } : g))}><option value={match.playerAId}>{match.playerAName}</option><option value={match.playerBId}>{match.playerBName}</option></select><input className="input" placeholder="Mbappé" value={goal.scorerName} onChange={(e) => setGoals(goals.map((g, i) => i === index ? { ...g, scorerName: e.target.value } : g))}/><input className="input" type="number" min={1} value={goal.quantity} onChange={(e) => setGoals(goals.map((g, i) => i === index ? { ...g, quantity: Number(e.target.value) } : g))}/></div>)}<button className="btn btn-ghost w-full" onClick={() => setGoals([...goals, { playerOwnerId: match.playerAId || '', playerOwnerName: match.playerAName, scorerName: '', quantity: 1 }])}>+ goleador</button></div><button className="btn btn-primary mt-5 w-full" onClick={async () => { await closeMatch(match, scoreA, scoreB, goals); onSaved(); }}><Save className="h-4 w-4"/> Cerrar partido y avanzar ganador</button>{match.round === 'FINAL' && <p className="mt-3 text-center text-sm text-pending"><Trophy className="inline h-4 w-4"/> Esto corona campeón y finaliza el torneo.</p>}</div></div>;
}
function ScoreBox({ name, value, setValue }) { return <label className="rounded-3xl bg-white/5 p-4 text-center"><span className="text-sm font-black">{name}</span><input className="mt-2 w-full bg-transparent text-center text-6xl font-black outline-none" type="number" min={0} value={value} onChange={(e) => setValue(Number(e.target.value))}/></label>; }
