import { useEffect, useState } from 'react';
import { AdminLayout } from '../components/AdminLayout';
import { WhatsAppInviteCard } from '../components/WhatsAppInviteCard';
import { auth } from '../lib/firebase';
import { listParticipants } from '../lib/firestore';
import type { Participant } from '../types';
export function AdminInvitesPage({ id }: { id: string }) { const [participants, setParticipants] = useState<Participant[]>([]); const [urls, setUrls] = useState<Record<string, string>>({}); useEffect(() => { listParticipants(id).then(setParticipants); }, [id]); async function createInvite(userId: string) { const token = await auth.currentUser?.getIdToken(); const response = await fetch('/api/admin/create-invite', { method: 'POST', headers: { 'Content-Type': 'application/json', Authorization: `Bearer ${token}` }, body: JSON.stringify({ userId, tournamentId: id }) }); const payload = await response.json() as { inviteUrl?: string; error?: string }; if (!response.ok || !payload.inviteUrl) throw new Error(payload.error ?? 'No se pudo generar invite'); setUrls((current) => ({ ...current, [userId]: payload.inviteUrl! })); }
  async function generateAll() { const token = await auth.currentUser?.getIdToken(); const response = await fetch('/api/admin/generate-invites-for-tournament', { method: 'POST', headers: { 'Content-Type': 'application/json', Authorization: `Bearer ${token}` }, body: JSON.stringify({ tournamentId: id }) }); const payload = await response.json() as { invites?: { userId: string; inviteUrl: string }[] }; setUrls(Object.fromEntries((payload.invites ?? []).map((i) => [i.userId, i.inviteUrl]))); }
  return <AdminLayout><div className="space-y-6"><div className="flex flex-wrap items-center justify-between gap-3"><div><h1 className="text-4xl font-black">Invites WhatsApp</h1><p className="text-slate-400">El token real se muestra solo en esta respuesta para copiar y enviar.</p></div><button className="btn btn-primary" onClick={() => void generateAll()}>Generar todos</button></div><div className="grid gap-3 md:grid-cols-2">{participants.map((p) => <div key={p.id} className="space-y-2"><WhatsAppInviteCard participant={p} inviteUrl={urls[p.userId]} />{!urls[p.userId] && <button className="btn btn-ghost w-full" onClick={() => void createInvite(p.userId)}>Generar invite</button>}</div>)}</div></div></AdminLayout>; }
